@startuml

actor Admin
boundary "Dashboard Page" as DashboardPage 
control "Auth Controller" as AuthController
entity "User" as User

Admin -> DashboardPage : Open Dashboard Page
activate DashboardPage
DashboardPage -> AuthController : actionChangePassword()    
activate AuthController
AuthController -> User : checkOldPassword()
activate User
User --> AuthController : return valid or invalid

alt Password is valid
    AuthController -> User : save()
    deactivate User
    AuthController -> DashboardPage : redirect()
else Password is invalid
    AuthController -> DashboardPage : redirect()
end

@enduml