@startuml

actor Admin
boundary "Forgot Password Page" as ForgotPasswordPage 
control "Auth Controller" as AuthController
entity "User" as User
entity "Password Reset" as PasswordReset

Admin -> ForgotPasswordPage : Open ForgotPassword Page
activate ForgotPasswordPage
ForgotPasswordPage -> AuthController : viewForgotPassword()
activate AuthController
AuthController -> ForgotPasswordPage : return page
ForgotPasswordPage -> AuthController : actionForgotPassword()    
AuthController -> User : checkEmail()
activate User
User --> AuthController : return valid or invalid
deactivate User
alt Email is valid
    AuthController -> PasswordReset : save()
    activate PasswordReset
    deactivate PasswordReset
    AuthController -> User : sendEmail()
    activate User
    deactivate User
    AuthController -> ForgotPasswordPage : redirect()
else Password is invalid
    AuthController -> ForgotPasswordPage : redirect()
end

@enduml