@startuml

actor Admin
boundary "Reset Password Page" as ResetPasswordPage 
control "Auth Controller" as AuthController
entity "User" as User
entity "Reset Password Token" as PasswordReset

Admin -> ResetPasswordPage : Open ResetPassword Page
activate ResetPasswordPage
ResetPasswordPage -> AuthController : viewResetPassword()
activate AuthController
AuthController -> ResetPasswordPage : return page
ResetPasswordPage -> AuthController : actionResetPassword()    
AuthController -> PasswordReset : checkToken()
activate PasswordReset
PasswordReset --> AuthController : return valid or invalid

alt Token is valid
    AuthController -> User : save()
    deactivate User
    AuthController -> ResetPasswordPage : redirect()
else Token is invalid
    AuthController -> ResetPasswordPage : redirect()
end

@enduml